apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-rwx
  namespace: kubeflow
spec:
  storageClassName: openebs-rwx
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s