apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc-volume
  namespace: admin
spec:
  storageClassName: openebs-rwx
  volumeName: minio-pv-volume
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi