apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc-rwx
  namespace: kubeflow
spec:
  storageClassName: openebs-rwx
  volumeName: minio-pv-rwx
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi