apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc-volume
  namespace: admin
spec:
  storageClassName: openebs-rwx
  volumeName: storage-pv-volume
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi